//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Code_CH.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Animation
    {
        public int idAnimation { get; set; }
        public string Img_animation_1 { get; set; }
        public string Img_animation_2 { get; set; }
        public string Img_animation_3 { get; set; }
        public string Img_animation_4 { get; set; }
        [NotMapped]
        public HttpPostedFileBase imageUploader { get; set; }
        [NotMapped]
        public HttpPostedFileBase imageUploader2 { get; set; }
        [NotMapped]
        public HttpPostedFileBase imageUploader3 { get; set; }
        [NotMapped]
        public HttpPostedFileBase imageUploader4 { get; set; }
    }
}
