//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Code_CH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoCaoDoanhThu
    {
        public int maTK { get; set; }
        public Nullable<System.DateTime> ngayTK { get; set; }
        public Nullable<int> soluongTon { get; set; }
        public Nullable<int> soluongXuat { get; set; }
        public Nullable<double> doanhThu { get; set; }
    }
}
