//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Code_CH.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class DauSanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DauSanPham()
        {
            this.SanPhams = new HashSet<SanPham>();
        }
    
        public int maDSP { get; set; }
        public string tenSP { get; set; }
        public string loaiSP { get; set; }
        public string hinhanhSP { get; set; }
        public Nullable<int> soluongSP { get; set; }
        public Nullable<double> giaSP { get; set; }
        public string hinhanhphu1 { get; set; }
        public string hinhanhphu2 { get; set; }
        public string hinhanhphu3 { get; set; }
        public string hinhanhphu4 { get; set; }
        public string hinhanhphu5 { get; set; }
        public string ghichu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [NotMapped]
        public HttpPostedFileBase imageUploader { get; set; }
        [NotMapped]
        public HttpPostedFileBase imageUploader2 { get; set; }
        [NotMapped]
        public HttpPostedFileBase imageUploader3 { get; set; }
        [NotMapped]
        public HttpPostedFileBase imageUploader4 { get; set; }
        [NotMapped]
        public HttpPostedFileBase imageUploader5 { get; set; }
        [NotMapped]
        public HttpPostedFileBase imageUploader6 { get; set; }

        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}
