//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Code_CH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HD()
        {
            this.ChiTietHoaDons = new HashSet<ChiTietHoaDon>();
        }
    
        public int maHD { get; set; }
        public Nullable<int> maKH { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<double> TongHD { get; set; }
        public string ghichuHD { get; set; }
        public string diachiPhu { get; set; }
        public Nullable<int> maTT { get; set; }
        public Nullable<int> soluong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        public virtual TaiKhoanKhachHang TaiKhoanKhachHang { get; set; }
        public virtual TrinhTrangDonHang TrinhTrangDonHang { get; set; }
    }
}
