//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Code_CH.Models
{
    using System;
    using System.Collections.Generic;

    interface ProxyEntity
    {
        void addTaiKhoanDB(CuaHangEntities database);
    }
    public partial class TaiKhoanKhachHang : ProxyEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaiKhoanKhachHang()
        {
            this.HDs = new HashSet<HD>();
        }
    
        public int maKH { get; set; }
        public string tenKH { get; set; }
        public string diachiKH { get; set; }
        public string emailKH { get; set; }
        public string sodienthoaiKH { get; set; }
        public Nullable<int> maTT { get; set; }
        public string Password { get; set; }
        public string huyenKH { get; set; }
        public string tinhKH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HD> HDs { get; set; }
        public virtual TinhTrangTaiKhoan TinhTrangTaiKhoan { get; set; }

        public void addTaiKhoanDB(CuaHangEntities database)
        {
            database.Entry(this).State = System.Data.Entity.EntityState.Modified;
            database.SaveChanges();
        }
    }
    public class ProxyTaiKhoan : ProxyEntity
    {
        private TaiKhoanKhachHang _taikhoan;

        public ProxyTaiKhoan(TaiKhoanKhachHang tk)
        {
            _taikhoan = tk;
        }

        public void addTaiKhoanDB(CuaHangEntities database)
        {
            string notAllowAddress = "Không địa chỉ"; 
            string notAllowPhone = "0123456789";
            var checkAddress = _taikhoan.diachiKH.Contains(notAllowAddress);
            var checkPhone = _taikhoan.sodienthoaiKH.Contains(notAllowPhone);

            if (checkAddress == false && checkPhone == false)
            {
                _taikhoan.addTaiKhoanDB(database);
            }
        }

       
    }
}
